FROM ubuntu:18.04 as ubuntu_base

ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

RUN apt-get update -q && \
    apt-get upgrade -q -y && \
    apt-get install -y \
            build-essential \
            git-core \
            libssl-dev \
            automake \
            autoconf \
            libncurses5-dev \
            curl \
            unzip

RUN apt-get clean -q -y && \
    apt-get autoclean -q -y && \
    apt-get autoremove -q -y && \
    rm -rf /var/cache/debconf/*-old && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /usr/share/doc/*

RUN git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.3

FROM ubuntu_base

RUN /bin/bash -c "PATH=${HOME}/.asdf/bin:/${HOME}/.asdf/shims:${PATH} && \
    asdf plugin-add erlang && \
    asdf install erlang 22.0.4 && \
    asdf global erlang 22.0.4 && \
    rm -rf  /tmp/*"

RUN /bin/bash -c "PATH=${HOME}/.asdf/bin:/${HOME}/.asdf/shims:${PATH} && \
    asdf plugin-add elixir && \
    asdf install elixir 1.9.0-otp-22 && \
    asdf global elixir 1.9.0-otp-22 && \
    rm -rf  /tmp/*"


RUN /bin/bash -c "PATH=${HOME}/.asdf/bin:/${HOME}/.asdf/shims:${PATH} && mix local.hex --force"
RUN /bin/bash -c "PATH=${HOME}/.asdf/bin:/${HOME}/.asdf/shims:${PATH} && mix local.rebar --force"
